# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FuraGal - A CNC aberta do Recuncho Maker
email: furagal@recunchomaker.com
description: > # this means to ignore newlines until "baseurl:"
  FuraGal e unha verdadeira cortadora por control numérico semi profesional de
  baixo custo, completamente open hardware.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://recunchomaker.org/furagal" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
